'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import EmployeeShell from '@/components/employee/EmployeeShell'

export default function CreateReportPage() {
  const router = useRouter(); const [form, setForm] = useState({ reportDate: '', title: '', description: '', workStartAt: '08:00', workEndAt: '17:00' }); const [error, setError] = useState('')
  const submit = async (event) => { event.preventDefault(); const response = await fetch('/api/employee/work-reports', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) return setError(data.message); router.push('/employee/work-reports') }
  return <EmployeeShell><header className="mb-8"><h1 className="text-2xl font-semibold">Buat Laporan Kerja</h1><p className="mt-1 text-sm text-slate-500">Laporkan pekerjaan yang telah dilakukan.</p></header><form onSubmit={submit} className="max-w-2xl space-y-5 rounded-xl border border-slate-200 bg-white p-8 shadow-sm">{error && <p className="rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<label className="block text-sm font-medium">Tanggal<input required type="date" value={form.reportDate} onChange={(e) => setForm({ ...form, reportDate: e.target.value })} className="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="block text-sm font-medium">Judul<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block text-sm font-medium">Mulai<input required type="time" value={form.workStartAt} onChange={(e) => setForm({ ...form, workStartAt: e.target.value })} className="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><label className="block text-sm font-medium">Selesai<input required type="time" value={form.workEndAt} onChange={(e) => setForm({ ...form, workEndAt: e.target.value })} className="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label></div><label className="block text-sm font-medium">Deskripsi<textarea required rows="6" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} className="mt-2 block w-full rounded-lg border border-slate-300 px-3 py-2.5" /></label><button className="rounded-lg bg-emerald-600 px-5 py-2.5 font-semibold text-white">Simpan Laporan</button></form></EmployeeShell>
}