'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'

function Icon({ children, size = 20 }) { return <span className="material-symbols-outlined" style={{ fontSize: size }}>{children}</span> }

export default function NotificationsPage() {
  const [notifications, setNotifications] = useState([])
  const [unreadCount, setUnreadCount] = useState(0)
  useEffect(() => { fetch('/api/notifications').then((response) => response.json()).then((data) => { setNotifications(data.notifications || []); setUnreadCount(data.unreadCount || 0) }) }, [])
  const markRead = async (id) => { await fetch('/api/notifications', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ id }) }); setNotifications((items) => items.map((item) => item.id === id ? { ...item, read_at: new Date().toISOString() } : item)); setUnreadCount((count) => Math.max(0, count - 1)) }
  const markAllRead = async () => { await fetch('/api/notifications', { method: 'PATCH' }); setNotifications((items) => items.map((item) => ({ ...item, read_at: new Date().toISOString() }))); setUnreadCount(0) }
  return <div className="font-dashboard min-h-screen bg-[#f7f9fb] text-slate-900"><aside className="fixed inset-y-0 left-0 z-50 hidden w-[280px] flex-col border-r border-slate-200 bg-white md:flex"><Link href="/dashboard" className="flex items-center gap-3 px-6 py-6"><img src="/images/logo.png" alt="Sebisa Presensi" className="h-16 w-16 object-contain" /><div><strong className="block text-base">Sebisa Presensi</strong><span className="text-xs text-slate-500">Employee Portal</span></div></Link><nav className="flex flex-1 flex-col gap-1 px-3"><Link href="/dashboard" className="flex gap-3 rounded-lg px-3 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-100"><Icon>dashboard</Icon>Dashboard</Link><Link href="/employee/clock" className="flex gap-3 rounded-lg px-3 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-100"><Icon>schedule</Icon>Presensi</Link><Link href="/profile" className="flex gap-3 rounded-lg px-3 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-100"><Icon>person</Icon>Profil</Link></nav></aside><main className="min-h-screen pb-12 pt-8 md:ml-[280px] md:pt-16"><div className="mx-auto max-w-[1000px] px-6 md:px-8"><section className="mb-6 flex items-end justify-between gap-3"><div><h1 className="text-2xl font-semibold">Notifikasi</h1><p className="mt-1 text-sm text-slate-500">Pesan yang tersimpan untuk akun Anda.</p></div>{unreadCount > 0 && <button onClick={markAllRead} className="rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-semibold">Tandai Semua Dibaca</button>}</section><div className="space-y-2">{notifications.map((notification) => { const payload = notification.data || {}; const title = payload.title || payload.subject || notification.type; const message = payload.message || payload.body || 'Notifikasi baru'; return <button key={notification.id} onClick={() => !notification.read_at && markRead(notification.id)} className={`flex w-full items-start gap-4 rounded-xl border p-6 text-left shadow-sm ${notification.read_at ? 'border-slate-200 bg-white' : 'border-emerald-200 bg-emerald-50/50'}`}><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-emerald-50 text-emerald-600"><Icon>{notification.read_at ? 'notifications' : 'mark_email_unread'}</Icon></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="text-sm font-semibold">{title}</p>{!notification.read_at && <span className="h-2 w-2 rounded-full bg-emerald-500" />}</div><p className="mt-1 text-sm text-slate-500">{message}</p><p className="mt-2 text-xs text-slate-500">{notification.created_at ? new Date(notification.created_at).toLocaleString('id-ID') : '-'}</p></div></button> })}</div>{notifications.length === 0 && <div className="rounded-xl border border-slate-200 bg-white px-5 py-12 text-center text-sm text-slate-500"><Icon size={40}>notifications_off</Icon><p className="mt-2">Belum ada notifikasi dari database.</p></div>}</div></main></div>
}